version: '3.4'
services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
    healthcheck: 
      test: ["CMD", "pg_isready", "-U", "myuser", "-d", "mydatabase"]
      interval: 15s
      timeout: 1m
      retries: 10
      start_period: 20s
    ports:
      - "5432:5432"


  create_tables:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://myuser:password@db:5432/mydatabase"
    command: ["python3", "create.py"]

  load_data:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://myuser:password@db:5432/mydatabase"
    command: ["python3", "load.py"]


  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://myuser:password@db:5432/mydatabase"
    command: ["python3", "main.py"]
    ports:
      - "5000:5000"  


