version: '3'
services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
    ports:
      - "5432:5432"


  create_tables:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://myuser:password@db:5432/mydatabase"
    command: ["python3", "create.py"]

  load_data:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://myuser:password@db:5432/mydatabase"
    command: ["python3", "load.py"]


  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://myuser:password@db:5432/mydatabase"
    command: ["python3", "main.py"]
    ports:
      - "5000:5000"  


